name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
           activate-environment: olhd
           environment-file: environment.yml
           python-version: 3.9
           auto-activate-base: false

    - name: run tests
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        pytest --cov=olhd --cov-report=xml
        # We want to make sure proper formatting of the notebooks.
        flake8-nb; [ $? -eq 0 ] || exit 1
        black-nb --check .; [ $? -eq 0 ] || exit 1
    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
